"""empty message

Revision ID: 2cacfc9a890a
Revises: f49260ff8b5c
Create Date: 2025-10-16 09:40:34.074362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cacfc9a890a'
down_revision = 'f49260ff8b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=100), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('mark')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mark', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('action')

    # ### end Alembic commands ###
