"""Add multi-site support

Revision ID: 5ff63285ca2d
Revises: f1dca01b7784
Create Date: 2025-10-16 11:57:38.012711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff63285ca2d'
down_revision = 'f1dca01b7784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if sites table exists before creating it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'sites' not in tables:
        # Create sites table if it doesn't exist
        op.create_table('sites',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
        sa.UniqueConstraint('name')
        )
    
    op.create_table('user_sites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'site_id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_groups_site_id', 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inventory_site_id', 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('inventory_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inventory_usage_site_id', 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_lecturers_site_id', 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('machine_maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_machine_maintenance_site_id', 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_machines_site_id', 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('macroplan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_macroplan_site_id', 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_modules_site_id', 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('overhead_cost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_overhead_cost_site_id', 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_schedule_site_id', 'sites', ['site_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_students_site_id', 'sites', ['site_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('fk_schedule_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('overhead_cost', schema=None) as batch_op:
        batch_op.drop_constraint('fk_overhead_cost_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_modules_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('macroplan', schema=None) as batch_op:
        batch_op.drop_constraint('fk_macroplan_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_machines_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('machine_maintenance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_machine_maintenance_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lecturers_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('inventory_usage', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_usage_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_groups_site_id', type_='foreignkey')
        batch_op.drop_column('site_id')

    op.drop_table('user_sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
