"""Add session_type, module_name, capacity, notes to Schedule

Revision ID: f1dca01b7784
Revises: 2cacfc9a890a
Create Date: 2025-10-16 11:22:09.574421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dca01b7784'
down_revision = '2cacfc9a890a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('session_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('capacity')
        batch_op.drop_column('session_type')
        batch_op.drop_column('module_name')

    # ### end Alembic commands ###
