"""Add student_task_id

Revision ID: f49260ff8b5c
Revises: e666b97b4aa4
Create Date: 2025-05-02 09:21:47.421313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49260ff8b5c'
down_revision = 'e666b97b4aa4'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('inventory_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_task_id', sa.Integer(), nullable=True))
        batch_op.alter_column('consumable',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('unit_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.create_foreign_key(
            'fk_inventory_task',
            'student_mini_task_progress',
            ['student_task_id'],
            ['id']
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('unit_cost',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('consumable',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('student_task_id')

    # ### end Alembic commands ###
